language: ruby
rvm:
  - 2.3.0

cache:
  directories:
    - vendor/bundler

before_install:
  - touch Gemfile

install:
  - make install

script:
  - make ci

notifications:
  email:
    on_success: never
    on_failure: change
  slack: votestakes:wlFrOcSeyGrsFf7SvoBftZxE
